"use client";

/**
 * design-preview/page.tsx — generated by Fish
 *
 * A live preview of your design system using real shadcn components
 * and your actual CSS tokens. Use the toolbar (bottom-right) to
 * tweak primary color, border radius, dark/light mode, and typography
 * before writing a single real feature.
 *
 * Route: /design-preview
 * Delete this file when you no longer need it, or keep as a living reference.
 */

import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Switch } from "@/components/ui/switch";
import { Skeleton } from "@/components/ui/skeleton";
import {
  LayoutDashboard,
  FolderOpen,
  CheckSquare,
  Inbox,
  Settings,
  Bell,
  Search,
  Plus,
  TrendingUp,
  Users,
  Activity,
  ChevronRight,
  Palette,
  Sun,
  Moon,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type FontOption = { label: string; value: string; stack: string };

const FONT_OPTIONS: FontOption[] = [
  { label: "Geist Sans", value: "geist",    stack: "'Geist Sans', 'Inter', sans-serif" },
  { label: "Inter",      value: "inter",    stack: "'Inter', sans-serif" },
  { label: "DM Sans",    value: "dm-sans",  stack: "'DM Sans', sans-serif" },
  { label: "IBM Plex",   value: "ibm-plex", stack: "'IBM Plex Sans', sans-serif" },
];

const RADIUS_LABELS: Record<string, string> = {
  "0":      "None",
  "0.25":   "XS",
  "0.375":  "SM",
  "0.5":    "MD",
  "0.75":   "LG",
  "1":      "XL",
};

const NAV_ITEMS = [
  { icon: LayoutDashboard, label: "Dashboard",  active: true  },
  { icon: FolderOpen,      label: "Projects",   active: false },
  { icon: CheckSquare,     label: "Tasks",      active: false },
  { icon: Inbox,           label: "Inbox",      active: false },
  { icon: Settings,        label: "Settings",   active: false },
];

const STAT_CARDS = [
  { label: "Total Projects", value: "24",  delta: "+3 this week",  icon: FolderOpen,  trend: "up"   },
  { label: "Active Tasks",   value: "138", delta: "12 due today",  icon: CheckSquare, trend: "warn" },
  { label: "Team Members",   value: "8",   delta: "+1 this month", icon: Users,       trend: "up"   },
  { label: "Completed",      value: "91%", delta: "+4% vs last",   icon: TrendingUp,  trend: "up"   },
];

const TASK_ROWS = [
  { title: "Design system audit",    status: "In Progress", priority: "High",   assignee: "VS" },
  { title: "API rate limit refactor",status: "Todo",        priority: "Medium", assignee: "CM" },
  { title: "Onboarding flow copy",   status: "Review",      priority: "Low",    assignee: "VS" },
  { title: "Mobile nav breakpoints", status: "Todo",        priority: "High",   assignee: "CM" },
  { title: "Analytics dashboard",    status: "In Progress", priority: "Medium", assignee: "VS" },
];

const STATUS_STYLES: Record<string, string> = {
  "In Progress": "bg-primary/10 text-primary border-primary/20",
  "Todo":        "bg-muted text-muted-foreground border-border",
  "Review":      "bg-amber-500/10 text-amber-600 border-amber-500/20 dark:text-amber-400",
  "Done":        "bg-emerald-500/10 text-emerald-600 border-emerald-500/20 dark:text-emerald-400",
};

const PRIORITY_STYLES: Record<string, string> = {
  "High":   "text-destructive",
  "Medium": "text-muted-foreground",
  "Low":    "text-muted-foreground/60",
};

// ---------------------------------------------------------------------------
// Toolbar
// ---------------------------------------------------------------------------

function hexToHsl(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

interface ToolbarProps {
  primaryHex:    string;
  radius:        string;
  darkMode:      boolean;
  fontValue:     string;
  onPrimary:     (v: string) => void;
  onRadius:      (v: string) => void;
  onDarkMode:    (v: boolean) => void;
  onFont:        (v: string) => void;
}

function Toolbar({ primaryHex, radius, darkMode, fontValue, onPrimary, onRadius, onDarkMode, onFont }: ToolbarProps) {
  const [open, setOpen] = useState(true);

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-2">
      {open && (
        <Card className="w-72 shadow-xl border-border">
          <CardHeader className="pb-3 pt-4 px-4">
            <CardTitle className="text-sm flex items-center gap-2">
              <Palette className="h-4 w-4 text-primary" />
              Design Token Playground
            </CardTitle>
            <CardDescription className="text-xs">
              Edits CSS variables live. Changes are not persisted.
            </CardDescription>
          </CardHeader>
          <CardContent className="px-4 pb-4 space-y-4">
            {/* Primary color */}
            <div className="space-y-1.5">
              <Label className="text-xs font-medium">Primary color</Label>
              <div className="flex items-center gap-3">
                <input
                  type="color"
                  value={primaryHex}
                  onChange={(e) => onPrimary(e.target.value)}
                  className="h-8 w-8 cursor-pointer rounded-md border border-border bg-transparent p-0.5"
                />
                <span className="text-xs text-muted-foreground font-mono">{primaryHex.toUpperCase()}</span>
              </div>
            </div>

            <Separator />

            {/* Radius */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <Label className="text-xs font-medium">Border radius</Label>
                <span className="text-xs text-muted-foreground">
                  {RADIUS_LABELS[radius] ?? radius}rem
                </span>
              </div>
              <input
                type="range"
                min={0}
                max={1}
                step={0.125}
                value={parseFloat(radius)}
                onChange={(e) => onRadius(e.target.value)}
                className="w-full accent-primary h-1.5"
              />
            </div>

            <Separator />

            {/* Dark mode */}
            <div className="flex items-center justify-between">
              <Label className="text-xs font-medium flex items-center gap-1.5">
                {darkMode ? <Moon className="h-3.5 w-3.5" /> : <Sun className="h-3.5 w-3.5" />}
                {darkMode ? "Dark mode" : "Light mode"}
              </Label>
              <Switch checked={darkMode} onCheckedChange={onDarkMode} />
            </div>

            <Separator />

            {/* Typography */}
            <div className="space-y-1.5">
              <Label className="text-xs font-medium">Typography</Label>
              <div className="grid grid-cols-2 gap-1.5">
                {FONT_OPTIONS.map((f) => (
                  <button
                    key={f.value}
                    onClick={() => onFont(f.value)}
                    className={`rounded-md border px-2 py-1.5 text-xs transition-colors text-left ${
                      fontValue === f.value
                        ? "border-primary bg-primary/10 text-primary font-medium"
                        : "border-border bg-background text-muted-foreground hover:border-primary/40"
                    }`}
                    style={{ fontFamily: f.stack }}
                  >
                    {f.label}
                  </button>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <Button
        size="sm"
        variant={open ? "outline" : "default"}
        className="h-9 gap-2 shadow-md"
        onClick={() => setOpen(!open)}
      >
        <Palette className="h-4 w-4" />
        {open ? "Hide" : "Design tokens"}
      </Button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Sidebar
// ---------------------------------------------------------------------------

function Sidebar() {
  return (
    <aside className="flex h-full w-56 flex-col border-r border-border bg-background">
      <div className="flex h-14 items-center gap-2 border-b border-border px-4">
        <div className="h-6 w-6 rounded-md bg-primary" />
        <span className="text-sm font-semibold tracking-tight">YourProject</span>
      </div>

      <nav className="flex-1 space-y-0.5 p-2 pt-3">
        {NAV_ITEMS.map((item) => (
          <button
            key={item.label}
            className={`flex w-full items-center gap-2.5 rounded-md px-3 py-2 text-sm transition-colors ${
              item.active
                ? "bg-primary/10 text-primary font-medium"
                : "text-muted-foreground hover:bg-muted hover:text-foreground"
            }`}
          >
            <item.icon className="h-4 w-4 shrink-0" />
            {item.label}
          </button>
        ))}
      </nav>

      <div className="border-t border-border p-3">
        <button className="flex w-full items-center gap-2.5 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground transition-colors">
          <Avatar className="h-6 w-6">
            <AvatarFallback className="text-[10px] bg-primary/10 text-primary">VS</AvatarFallback>
          </Avatar>
          <div className="flex-1 text-left">
            <p className="text-xs font-medium text-foreground leading-none">Vish S.</p>
            <p className="text-[10px] text-muted-foreground mt-0.5">Admin</p>
          </div>
        </button>
      </div>
    </aside>
  );
}

// ---------------------------------------------------------------------------
// Main content
// ---------------------------------------------------------------------------

function MainContent() {
  return (
    <main className="flex-1 overflow-auto">
      {/* Top bar */}
      <header className="flex h-14 items-center justify-between border-b border-border bg-background px-6">
        <div className="flex items-center gap-3">
          <h1 className="text-sm font-semibold">Dashboard</h1>
          <ChevronRight className="h-4 w-4 text-muted-foreground" />
          <span className="text-sm text-muted-foreground">Overview</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder="Search…" className="h-8 w-52 pl-8 text-sm" />
          </div>
          <Button variant="outline" size="sm" className="h-8 gap-1.5">
            <Bell className="h-3.5 w-3.5" />
            <Badge className="h-4 px-1.5 text-[10px] rounded-full">3</Badge>
          </Button>
          <Button size="sm" className="h-8 gap-1.5">
            <Plus className="h-3.5 w-3.5" />
            New
          </Button>
        </div>
      </header>

      <div className="p-6 space-y-6">
        {/* Stats */}
        <div className="grid grid-cols-4 gap-4">
          {STAT_CARDS.map((s) => (
            <Card key={s.label}>
              <CardContent className="p-4">
                <div className="flex items-start justify-between">
                  <div className="space-y-1">
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                    <p className="text-2xl font-semibold tracking-tight">{s.value}</p>
                    <p className={`text-xs ${s.trend === "up" ? "text-emerald-600 dark:text-emerald-400" : "text-amber-600 dark:text-amber-400"}`}>
                      {s.delta}
                    </p>
                  </div>
                  <div className="rounded-md bg-muted p-2">
                    <s.icon className="h-4 w-4 text-muted-foreground" />
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Tabs section */}
        <Tabs defaultValue="tasks">
          <div className="flex items-center justify-between mb-3">
            <TabsList className="h-8">
              <TabsTrigger value="tasks"  className="text-xs h-7 px-3">Tasks</TabsTrigger>
              <TabsTrigger value="team"   className="text-xs h-7 px-3">Team</TabsTrigger>
              <TabsTrigger value="forms"  className="text-xs h-7 px-3">Forms</TabsTrigger>
              <TabsTrigger value="states" className="text-xs h-7 px-3">States</TabsTrigger>
            </TabsList>
            <Button variant="outline" size="sm" className="h-7 text-xs gap-1.5">
              <Plus className="h-3 w-3" />
              Add task
            </Button>
          </div>

          {/* Tasks tab */}
          <TabsContent value="tasks">
            <Card>
              <CardContent className="p-0">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Title</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Status</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Priority</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-muted-foreground">Assignee</th>
                    </tr>
                  </thead>
                  <tbody>
                    {TASK_ROWS.map((row, i) => (
                      <tr key={i} className="border-b border-border last:border-0 hover:bg-muted/40 transition-colors">
                        <td className="px-4 py-3 font-medium text-sm">{row.title}</td>
                        <td className="px-4 py-3">
                          <span className={`inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium ${STATUS_STYLES[row.status]}`}>
                            {row.status}
                          </span>
                        </td>
                        <td className={`px-4 py-3 text-xs font-medium ${PRIORITY_STYLES[row.priority]}`}>{row.priority}</td>
                        <td className="px-4 py-3">
                          <Avatar className="h-6 w-6">
                            <AvatarFallback className="text-[10px] bg-primary/10 text-primary">{row.assignee}</AvatarFallback>
                          </Avatar>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Team tab */}
          <TabsContent value="team">
            <Card>
              <CardContent className="p-4 space-y-3">
                {["Vish Swamy", "Chandana M.", "Alex R.", "Priya K."].map((name, i) => (
                  <div key={i} className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Avatar className="h-8 w-8">
                        <AvatarFallback className="text-xs bg-primary/10 text-primary">
                          {name.split(" ").map(n => n[0]).join("")}
                        </AvatarFallback>
                      </Avatar>
                      <div>
                        <p className="text-sm font-medium">{name}</p>
                        <p className="text-xs text-muted-foreground">{["Admin", "Manager", "Developer", "Designer"][i]}</p>
                      </div>
                    </div>
                    <Button variant="outline" size="sm" className="h-7 text-xs">Message</Button>
                  </div>
                ))}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Forms tab */}
          <TabsContent value="forms">
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="text-sm">New project</CardTitle>
                <CardDescription className="text-xs">All inputs use your design tokens.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="text-xs">Project name</Label>
                    <Input placeholder="e.g. Arel Dashboard" className="h-8 text-sm" />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs">Status</Label>
                    <Input placeholder="Active" className="h-8 text-sm" />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Description</Label>
                  <Input placeholder="One sentence about this project…" className="h-8 text-sm" />
                </div>
                <div className="flex items-center justify-between pt-1">
                  <div className="flex items-center gap-2">
                    <Switch id="shared" />
                    <Label htmlFor="shared" className="text-xs text-muted-foreground cursor-pointer">Share with team</Label>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" className="h-8 text-xs">Cancel</Button>
                    <Button size="sm" className="h-8 text-xs">Create project</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* States tab */}
          <TabsContent value="states">
            <div className="grid grid-cols-2 gap-4">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-xs text-muted-foreground uppercase tracking-wide">Buttons</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="flex flex-wrap gap-2">
                    <Button size="sm">Primary</Button>
                    <Button size="sm" variant="secondary">Secondary</Button>
                    <Button size="sm" variant="outline">Outline</Button>
                    <Button size="sm" variant="ghost">Ghost</Button>
                    <Button size="sm" variant="destructive">Destructive</Button>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-xs text-muted-foreground uppercase tracking-wide">Badges</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <div className="flex flex-wrap gap-2">
                    <Badge>Default</Badge>
                    <Badge variant="secondary">Secondary</Badge>
                    <Badge variant="outline">Outline</Badge>
                    <Badge variant="destructive">Destructive</Badge>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-xs text-muted-foreground uppercase tracking-wide">Loading states</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-4/5" />
                  <Skeleton className="h-4 w-3/5" />
                  <div className="flex items-center gap-3 pt-1">
                    <Skeleton className="h-8 w-8 rounded-full" />
                    <div className="space-y-1.5 flex-1">
                      <Skeleton className="h-3 w-full" />
                      <Skeleton className="h-3 w-2/3" />
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-xs text-muted-foreground uppercase tracking-wide">Typography</CardTitle>
                </CardHeader>
                <CardContent className="space-y-1">
                  <p className="text-2xl font-bold tracking-tight">Heading 2xl</p>
                  <p className="text-lg font-semibold">Heading lg</p>
                  <p className="text-base">Body text — base size</p>
                  <p className="text-sm text-muted-foreground">Secondary text — sm</p>
                  <p className="text-xs text-muted-foreground">Caption — xs</p>
                  <p className="text-xs font-mono text-muted-foreground mt-2">Monospace — code</p>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>

        {/* Activity feed */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-2">
              <Activity className="h-4 w-4 text-muted-foreground" />
              <CardTitle className="text-sm">Recent activity</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {[
                { msg: "Design system audit marked complete",    time: "2m ago",  dot: "bg-primary" },
                { msg: "New task added to Sprint 4",             time: "18m ago", dot: "bg-muted-foreground" },
                { msg: "Onboarding copy moved to Review",        time: "1h ago",  dot: "bg-amber-500" },
                { msg: "Chandana joined the project",            time: "3h ago",  dot: "bg-emerald-500" },
              ].map((item, i) => (
                <div key={i} className="flex items-start gap-3">
                  <span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${item.dot}`} />
                  <div className="flex-1 flex items-center justify-between">
                    <p className="text-sm">{item.msg}</p>
                    <span className="text-xs text-muted-foreground shrink-0 ml-4">{item.time}</span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function DesignPreviewPage() {
  const [primaryHex, setPrimaryHex] = useState("#000000");
  const [radius,     setRadius]     = useState("0.5");
  const [darkMode,   setDarkMode]   = useState(false);
  const [fontValue,  setFontValue]  = useState("geist");

  // Read initial values from computed CSS on mount
  useEffect(() => {
    const root  = document.documentElement;
    const style = getComputedStyle(root);
    const hsl   = style.getPropertyValue("--primary").trim();
    if (hsl) {
      // Convert HSL string "H S% L%" to a displayable hex approximation
      // We just keep a local hex state for the picker; actual token is HSL
    }
    const r = style.getPropertyValue("--radius").trim().replace("rem", "");
    if (r) setRadius(r);
    setDarkMode(root.classList.contains("dark"));
  }, []);

  const handlePrimary = useCallback((hex: string) => {
    setPrimaryHex(hex);
    const hsl = hexToHsl(hex);
    document.documentElement.style.setProperty("--primary", hsl);
    // Keep foreground readable on primary bg
    const [, , lRaw] = hsl.split(" ");
    const l = parseFloat(lRaw);
    document.documentElement.style.setProperty("--primary-foreground", l > 50 ? "0 0% 0%" : "0 0% 100%");
  }, []);

  const handleRadius = useCallback((val: string) => {
    setRadius(val);
    document.documentElement.style.setProperty("--radius", `${val}rem`);
  }, []);

  const handleDarkMode = useCallback((val: boolean) => {
    setDarkMode(val);
    document.documentElement.classList.toggle("dark", val);
  }, []);

  const handleFont = useCallback((val: string) => {
    setFontValue(val);
    const opt = FONT_OPTIONS.find(f => f.value === val);
    if (opt) document.documentElement.style.setProperty("--font-sans", opt.stack);
  }, []);

  return (
    <div className="flex h-screen overflow-hidden bg-background text-foreground" style={{ fontFamily: "var(--font-sans, sans-serif)" }}>
      <Sidebar />
      <MainContent />
      <Toolbar
        primaryHex={primaryHex}
        radius={radius}
        darkMode={darkMode}
        fontValue={fontValue}
        onPrimary={handlePrimary}
        onRadius={handleRadius}
        onDarkMode={handleDarkMode}
        onFont={handleFont}
      />
    </div>
  );
}
